PNPM_DIRECTORY should be relative to approot

diff --git a/commands/web/pnpm b/commands/web/pnpm
--- a/commands/web/pnpm
+++ b/commands/web/pnpm
@@ -14,9 +14,9 @@ fi
 
 # If a $PNPM_DIRECTORY is set, run our PNPM commands in that directory
 if [ -n "$PNPM_DIRECTORY" ]; then
-  mkdir -p "$PNPM_DIRECTORY"
-  cd "$PNPM_DIRECTORY" || {
-    echo "Error: Failed to change directory to '$PNPM_DIRECTORY'." >&2
+  mkdir -p "$DDEV_APPROOT/$PNPM_DIRECTORY"
+  cd "$DDEV_APPROOT/$PNPM_DIRECTORY" || {
+    echo "Error: Failed to change directory to '$DDEV_APPROOT/$PNPM_DIRECTORY'." >&2
     exit 1
   }
 fi
